name = "wikisites-api"
main = "packages/workers/src/index.ts"
compatibility_date = "2026-06-07"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "encyclopeptide.com/api/*"
zone_name = "encyclopeptide.com"

[[routes]]
pattern = "wikipept.com/api/*"
zone_name = "wikipept.com"
