import { defineConfig } from "astro/config";
import solid from "@astrojs/solid-js";
import tailwindcss from "@tailwindcss/vite";
import starlight from "@astrojs/starlight";
import remarkKatex from "./src/lib/remark-katex.ts";
import rehypeKatex from "./src/lib/rehype-katex.ts";

export default defineConfig({
  site: "https://wikipept.com",
  output: "static",
  trailingSlash: "always",
  markdown: {
    remarkPlugins: [remarkKatex],
    rehypePlugins: [rehypeKatex],
  },
  integrations: [
    starlight({
      title: "Wikipept",
      description: "Interactive, community-driven platform for learning oligopeptide biology",
      logo: {
        src: "./src/assets/logo.svg",
        alt: "Wikipept",
      },
      social: [],
      sidebar: [
        {
          label: "Learn",
          items: [
            { label: "Overview", slug: "learn" },
            { label: "20 Standard Amino Acids", slug: "learn/amino-acids" },
            { label: "Peptide Bond Chemistry", slug: "learn/peptide-bonds" },
            { label: "Protein Structure", slug: "learn/structure" },
            { label: "Peptide Signaling", slug: "learn/signaling" },
            { label: "Receptor Binding", slug: "learn/receptors" },
            { label: "Therapeutic Peptides", slug: "learn/pharmacology" },
            { label: "Solid-Phase Synthesis", slug: "learn/spps" },
            { label: "Purification Methods", slug: "learn/purification" },
            { label: "Computational Design", slug: "learn/computational" },
            { label: "Drug Delivery", slug: "learn/drug-delivery" },
            { label: "Clinical Trials", slug: "learn/clinical-trials" },
            { label: "Regulatory Pathways", slug: "learn/regulatory" },
          ],
        },
        {
          label: "Reference",
          items: [
            { label: "Peptide Database", slug: "reference/peptides" },
            { label: "Glossary", slug: "reference/glossary" },
            { label: "Comprehensive Glossary", slug: "reference/peptide-glossary-comprehensive" },
            { label: "Physicochemical Properties", slug: "reference/physicochemical-properties" },
            { label: "Receptor Binding Affinities", slug: "reference/receptor-binding" },
            { label: "Clinical Trials Database", slug: "reference/clinical-trials" },
            { label: "FDA-Approved Peptides", slug: "reference/approved-peptides" },
            { label: "Peptide Modifications", slug: "reference/peptide-modifications" },
            { label: "Amino Acid Codons", slug: "reference/amino-acid-codons" },
            { label: "Peptide Sequence Motifs", slug: "reference/peptide-sequence-motifs" },
            { label: "Drug Delivery Systems", slug: "reference/drug-delivery-systems" },
            { label: "Analytical Methods", slug: "reference/analytical-methods" },
            { label: "Peptide Databases", slug: "reference/peptide-databases" },
            { label: "Peptide Structures", slug: "reference/peptide-structures" },
            { label: "Peptide Generations", slug: "reference/peptide-generations" },
            { label: "Peptide Patents", slug: "reference/peptide-patents" },
            { label: "Peptide Market Data", slug: "reference/peptide-market-data" },
            { label: "Peptide Reimbursement", slug: "reference/peptide-reimbursement" },
            { label: "Peptide Interactions Database", slug: "reference/peptide-interactions-database" },
            { label: "Peptide Clinical Dosing", slug: "reference/peptide-clinical-dosing" },
            { label: "Peptide Storage Conditions", slug: "reference/peptide-storage-conditions" },
            { label: "Peptide Reconstitution Guide", slug: "reference/peptide-reconstitution-guide" },
            { label: "Peptide Compatibility", slug: "reference/peptide-compatibility" },
            { label: "Peptide Safety Data", slug: "reference/peptide-safety-data" },
            { label: "Peptide Cost Analysis", slug: "reference/peptide-cost-analysis" },
            { label: "Manufacturing Methods", slug: "reference/peptide-manufacturing-methods" },
            { label: "Quality Control", slug: "reference/peptide-quality-control" },
            { label: "Environmental Impact", slug: "reference/peptide-environmental-impact" },
            { label: "Drug Interactions (Complete)", slug: "reference/peptide-drug-interactions-complete" },
            { label: "Dosing (Complete)", slug: "reference/peptide-dosing-complete" },
            { label: "Storage (Complete)", slug: "reference/peptide-storage-complete" },
            { label: "Reconstitution (Complete)", slug: "reference/peptide-reconstitution-complete" },
            { label: "Safety (Complete)", slug: "reference/peptide-safety-complete" },
          ],
        },
        {
          label: "Interactive",
          items: [
            { label: "Quizzes", link: "/quizzes" },
            { label: "Daily Challenge", link: "/daily" },
            { label: "Flashcards", link: "/flashcards" },
            { label: "Review", link: "/review" },
          ],
        },
        {
          label: "Practical",
          items: [
            { label: "Reconstitution", slug: "learn/reconstitution" },
            { label: "Storage & Handling", slug: "learn/peptide-storage" },
            { label: "Safety", slug: "learn/peptide-safety" },
            { label: "Calculations", slug: "learn/peptide-calculations" },
            { label: "Impurities", slug: "learn/peptide-impurities" },
            { label: "Peptide Half-Life", slug: "learn/peptide-half-life" },
            { label: "Amino Acid Properties", slug: "learn/amino-acid-properties" },
            { label: "Peptide Drug Pipeline", slug: "learn/peptide-drug-pipeline" },
            { label: "SPPS Protocol", slug: "learn/spps-protocol" },
            { label: "HPLC Purification", slug: "learn/hplc-purification" },
            { label: "Mass Spectrometry", slug: "learn/mass-spectrometry-peptides" },
            { label: "Circular Dichroism", slug: "learn/circular-dichroism" },
            { label: "NMR Structure", slug: "learn/nmr-peptide-structure" },
            { label: "Semaglutide vs Tirzepatide", slug: "learn/semaglutide-vs-tirzepatide" },
            { label: "Semaglutide vs Liraglutide", slug: "learn/semaglutide-vs-liraglutide" },
            { label: "Semaglutide vs Liraglutide (Weight Loss)", slug: "learn/semaglutide-vs-liraglutide-weight-loss" },
            { label: "Tirzepatide vs Semaglutide (Weight Loss)", slug: "learn/tirzepatide-vs-semaglutide-weight-loss" },
            { label: "Mounjaro vs Ozempic", slug: "learn/mounjaro-vs-ozempic" },
            { label: "Retatrutide vs Tirzepatide", slug: "learn/retatrutide-vs-tirzepatide" },
            { label: "Glutathione vs NAC", slug: "learn/glutathione-vs-nac" },
            { label: "PT-141 vs Sildenafil", slug: "learn/pt-141-vs-viagra" },
            { label: "BPC-157 vs Thymosin Beta-4", slug: "learn/bpc-157-vs-thymosin-beta-4" },
            { label: "GHK-Cu vs BPC-157", slug: "learn/ghk-cu-vs-bpc-157" },
            { label: "Ipamorelin vs MK-677", slug: "learn/ipamorelin-vs-mk-677" },
            { label: "CJC-1295 vs Ipamorelin", slug: "learn/cjc-1295-vs-ipamorelin" },
            { label: "Insulin Glargine vs Detemir", slug: "learn/insulin-glargine-vs-detemir" },
            { label: "CJC-1295 vs Sermorelin", slug: "learn/cjc-1295-vs-sermorelin" },
            { label: "TB-500 vs BPC-157 (Recovery)", slug: "learn/tb-500-vs-bpc-157-recovery" },
            { label: "Melanotan I vs Melanotan II", slug: "learn/melanotan-i-vs-melanotan-ii" },
            { label: "Oxytocin vs Vasopressin", slug: "learn/oxytocin-vs-vasopressin" },
            { label: "Oxytocin vs Desmopressin", slug: "learn/oxytocin-vs-desmopressin" },
            { label: "NADH vs NADPH", slug: "learn/nadh-vs-nadph" },
            { label: "Heparin vs Enoxaparin", slug: "learn/heparin-vs-enoxaparin" },
            { label: "Testosterone vs GHRP-6", slug: "learn/testosterone-vs-ghrp-6" },
            { label: "BPC-157 Oral vs Injectable", slug: "learn/bpc-157-orally-vs-injectable" },
            { label: "CJC-1295 DAC vs No-DAC", slug: "learn/cjc-1295-dac-vs-no-dac" },
            { label: "Peptide Interactions", slug: "learn/peptide-interactions" },
            { label: "Insulin Aspart vs Lispro", slug: "learn/insulin-aspart-vs-lispro" },
            { label: "Insulin Lispro vs Aspart (Ultra-Rapid)", slug: "learn/insulin-lispro-vs-aspart-ultra-rapid" },
            { label: "Semaglutide vs Empagliflozin", slug: "learn/semaglutide-vs-empagliflozin" },
            { label: "BPC-157 vs KPV", slug: "learn/bpc-157-vs-kpv" },
            { label: "BPC-157 vs KPV Analysis", slug: "learn/bpc-157-vs-kvv-analysis" },
            { label: "Melanotan II vs PT-141", slug: "learn/melanotan-ii-vs-pt-141" },
            { label: "Melanotan I vs Afamelanotide", slug: "learn/melanotan-i-vs-afmelanotide" },
            { label: "CJC-1295 DAC vs Mod GRF", slug: "learn/cjc-1295-dac-vs-mod-grf-1-29" },
            { label: "GHK-Cu vs Copper Peptide-1", slug: "learn/ghk-cu-vs-copper-peptide-1" },
            { label: "Thymosin Alpha-1 vs Beta-4", slug: "learn/thymosin-alpha-1-vs-thymosin-beta-4" },
            { label: "Thymosin Beta-4 vs XTRA", slug: "learn/thymosin-beta-4-vs-xtra" },
            { label: "Oxymetazoline vs Brimonidine", slug: "learn/oxymetazoline-vs-brimonidine" },
            { label: "VIP vs PACAP", slug: "learn/vip-vs-pacap" },
            { label: "DSIP vs Orexin", slug: "learn/dsip-vs-orexin" },
            { label: "Liraglutide vs Dulaglutide", slug: "learn/liraglutide-vs-dulaglutide" },
            { label: "Insulin Degludec vs Glargine U-300", slug: "learn/insulin-degludec-vs-glargine-u300" },
            { label: "Bremelanotide vs UV-1502", slug: "learn/bremelanotide-vs-uv-1502" },
            { label: "Cagrilintide vs Amylin", slug: "learn/cagrilintide-vs-amylin" },
            { label: "Orforglipron vs Danuglipron", slug: "learn/orforglipron-vs-danuglipron" },
            { label: "Retatrutide vs Survodutide", slug: "learn/retatrutide-vs-survodutide" },
            { label: "Semaglutide Oral vs Injectable", slug: "learn/semaglutide-oral-vs-injectable" },
            { label: "GHK-Cu vs Melatonin", slug: "learn/ghk-cu-vs-melatonin" },
            { label: "TB-500 vs Growth Hormone", slug: "learn/tb-500-vs-growth-hormone" },
            { label: "VIP vs Sildenafil", slug: "learn/vip-vs-sildenafil" },
            { label: "Insulin Detemir vs Degludec", slug: "learn/insulin-detemir-vs-degludec" },
            { label: "Semaglutide vs Orforglipron", slug: "learn/semaglutide-vs-orforglipron" },
            { label: "BPC-157 vs GHK-Cu (Repair)", slug: "learn/bpc-157-vs-ghk-cu-tissue-repair" },
            { label: "CJC-1295 DAC + Ipamorelin Stack", slug: "learn/cjc-1295-dac-vs-ipamorelin-stack" },
            { label: "Melanotan II vs Afamelanotide", slug: "learn/melanotan-ii-vs-afmelanotide-freckles" },
            { label: "Oxytocin vs Ocitocin (Nasal)", slug: "learn/oxytocin-vs-ocitocin-nasal" },
            { label: "Thymosin Alpha-1 vs Thymulin", slug: "learn/thymosin-alpha-1-vs-thymulin" },
            { label: "VIP vs ACTH", slug: "learn/vip-vs-acth" },
            { label: "GHRP-2 vs GHRP-6 Selectivity", slug: "learn/ghrp-2-vs-ghrp-6-selectivity" },
            { label: "Insulin Aspart vs Glulisine", slug: "learn/insulin-aspart-vs-glulisine" },
            { label: "Insulin Glargine vs Peglispro", slug: "learn/insulin-glargine-vs-peglispro" },
            { label: "Semaglutide vs Cagrilintide Combo", slug: "learn/semaglutide-vs-cagrilintide-combo" },
            { label: "BPC-157 vs KPV Mechanism", slug: "learn/bpc-157-vs-kpv-mechanism" },
            { label: "CJC-1295 vs Sermorelin Comparison", slug: "learn/cjc-1295-vs-sermorelin-comparison" },
            { label: "Melanotan II vs PT-141 Selectivity", slug: "learn/melanotan-ii-vs-pt-141-selectivity" },
            { label: "Oxytocin vs Carbetocin", slug: "learn/oxytocin-vs-carbetocin" },
            { label: "Thymosin Beta-4 vs GHK-Cu Synergy", slug: "learn/thymosin-beta-4-vs-ghk-cu-synergy" },
            { label: "VIP vs PACAP Receptor", slug: "learn/vip-vs-pacap-receptor" },
            { label: "GHRP-6 vs MK-677 Orality", slug: "learn/ghrp-6-vs-mk-677-orality" },
            { label: "Insulin Degludec vs Icodec", slug: "learn/insulin-degludec-vs-icodec" },
            { label: "Insulin Glargine U-100 vs U-300", slug: "learn/insulin-glargine-u100-vs-u300" },
            { label: "Semaglutide vs Liraglutide (CV)", slug: "learn/semaglutide-vs-liraglutide-cardiovascular" },
            { label: "BPC-157 vs KPV (Gut Health)", slug: "learn/bpc-157-vs-kpv-gut-health" },
            { label: "CJC-1295 vs MK-677 (Combo)", slug: "learn/cjc-1295-vs-mk-677-combination" },
            { label: "Melanotan I vs II (Tanning)", slug: "learn/melanotan-i-vs-melanotan-ii-tanning" },
            { label: "Oxytocin vs Carbetocin", slug: "learn/oxytocin-vs-carbetocin-postpartum" },
            { label: "Thymosin Alpha-1 vs Interferon", slug: "learn/thymosin-alpha-1-vs-interferon" },
            { label: "VIP vs Sildenafil (ED)", slug: "learn/vip-vs-sildenafil-erectile" },
            { label: "GHRP-6 vs Ipamorelin (Side Effects)", slug: "learn/ghrp-6-vs-ipamorelin-side-effects" },
            { label: "Insulin Aspart vs Lispro (Onset)", slug: "learn/insulin-aspart-vs-lispro-onset" },
            { label: "Insulin Degludec vs Icodec (Weekly)", slug: "learn/insulin-degludec-vs-icodec-weekly" },
            { label: "Semaglutide vs Tirzepatide (Cost)", slug: "learn/semaglutide-vs-tirzepatide-cost" },
            { label: "BPC-157 vs TB-4 (Synergy)", slug: "learn/bpc-157-vs-thymosin-beta-4-synergy" },
            { label: "CJC-1295 DAC vs MK-677 (Stack)", slug: "learn/cjc-1295-dac-vs-mk-677-stack" },
            { label: "Melanotan II vs Afamelanotide (FDA)", slug: "learn/melanotan-ii-vs-afmelanotide-fda" },
            { label: "Oxytocin vs Eprosartan", slug: "learn/oxytocin-vs-eprosartan" },
            { label: "Thymosin Alpha-1 vs Vitamin D", slug: "learn/thymosin-alpha-1-vs-vitamin-d" },
            { label: "VIP vs L-Arginine", slug: "learn/vip-vs-l-arginine" },
            { label: "GHRP-6 vs L-DOPA", slug: "learn/ghrp-6-vs-l-dopa" },
            { label: "Insulin Lispro vs Technosphere", slug: "learn/insulin-lispro-vs-ultra-rapid-technosphere" },
            { label: "SPPS Troubleshooting", slug: "learn/peptide-synthesis-troubleshooting" },
            { label: "Peptide Characterization", slug: "learn/peptide-characterization" },
            { label: "Peptide Formulation", slug: "learn/peptide-formulation" },
            { label: "Peptide Stability Testing", slug: "learn/peptide-stability-testing" },
            { label: "Peptide Scale-Up", slug: "learn/peptide-scale-up" },
            { label: "Peptide Dosing Guide", slug: "learn/peptide-dosing-guide" },
            { label: "Peptide GMP Manufacturing", slug: "learn/peptide-gmp-manufacturing" },
            { label: "Peptide ICH Guidelines", slug: "learn/peptide-ich-guidelines" },
            { label: "Peptide Bioanalysis", slug: "learn/peptide-bioanalysis" },
            { label: "Peptide Pharmacokinetics", slug: "learn/peptide-pharmacokinetics" },
            { label: "Peptide Toxicology", slug: "learn/peptide-toxicology" },
            { label: "GMP Validation", slug: "learn/peptide-gmp-validation" },
            { label: "Technology Transfer", slug: "learn/peptide-technology-transfer" },
            { label: "Regulatory Submission", slug: "learn/peptide-regulatory-submission" },
            { label: "Clinical Trial Design", slug: "learn/peptide-clinical-trial-design" },
            { label: "Post-Market Surveillance", slug: "learn/peptide-post-market-surveillance" },
          ],
        },
        {
          label: "Tools",
          items: [
            { label: "MW Calculator", link: "/tools/molecular-weight-calculator" },
            { label: "Reconstitution Calculator", link: "/tools/reconstitution-calculator" },
            { label: "Peptide Property Calculator", link: "/tools/peptide-property-calculator" },
            { label: "Stability Predictor", link: "/tools/stability-predictor" },
            { label: "Interaction Checker", link: "/tools/interaction-checker" },
            { label: "Sequence Analyzer", link: "/tools/sequence-analyzer" },
            { label: "Peptide Discovery", link: "/tools/peptide-discovery" },
            { label: "Peptide Glossary", link: "/tools/glossary" },
            { label: "API Documentation", link: "/api/docs" },
          ],
        },
        {
          label: "Topics",
          items: [
            { label: "Amino Acids", link: "/topics/amino-acids" },
            { label: "Peptide Structure", link: "/topics/peptide-structure" },
            { label: "Peptide Synthesis", link: "/topics/peptide-synthesis" },
            { label: "Pharmacology", link: "/topics/pharmacology" },
            { label: "Receptors & Signaling", link: "/topics/receptors" },
            { label: "Drug Discovery", link: "/topics/drug-discovery" },
          ],
        },
        {
          label: "Community",
          items: [
            { label: "Get Involved", slug: "community" },
          ],
        },
      ],
      customCss: [
        "./src/styles/starlight.css",
      ],
    }),
    solid(),
  ],
  vite: {
    plugins: [tailwindcss()],
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            "solid-js": ["solid-js"],
          },
        },
      },
    },
  },
});
