#!/bin/bash
# Directory Submission Script for WikiPept
# Submit to 20 directories
# Run manually after account creation

set -e

echo "================================================"
echo "  WikiPept Directory Submission Script"
echo "================================================"
echo ""
echo "Before running, ensure you have:"
echo "1. Created accounts on all directories"
echo "2. Verified email addresses"
echo "3. Prepared project description"
echo ""
echo "Project: WikiPept (wikipept.com)"
echo "Description: Open-source peptide database and tools"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

echo ""
echo "Submitting to directories..."
echo ""

# Bioinformatics
echo "=== Bioinformatics Directories ==="
echo "1. Bioinformatics.org"
echo "   URL: https://www.bioinformatics.org"
echo "   Action: Create account → Submit project → Add link"
echo ""
echo "2. OpenBioinformatics.org"
echo "   URL: https://www.openbioinformatics.org"
echo "   Action: Create account → Submit project → Add link"
echo ""
echo "3. BioStars.org"
echo "   URL: https://www.biostars.org"
echo "   Action: Create account → Post project → Add link"
echo ""

# Science
echo "=== Science Directories ==="
echo "4. ScienceOpen.com"
echo "   URL: https://www.scienceopen.com"
echo "   Action: Create account → Submit project → Add link"
echo ""
echo "5. ResearchGate.net"
echo "   URL: https://www.researchgate.net"
echo "   Action: Create account → Submit project → Add link"
echo ""
echo "6. Academia.edu"
echo "   URL: https://www.academia.edu"
echo "   Action: Create account → Submit project → Add link"
echo ""

# Tools
echo "=== Tools Directories ==="
echo "7. AlternativeTo.net"
echo "   URL: https://www.alternativeto.net"
echo "   Action: Create account → Submit alternative → Add link"
echo ""
echo "8. ProductHunt.com"
echo "   URL: https://www.producthunt.com"
echo "   Action: Create account → Submit product → Add link"
echo ""
echo "9. Slant.co"
echo "   URL: https://www.slant.co"
echo "   Action: Create account → Submit product → Add link"
echo ""
echo "10. StackShare.io"
echo "   URL: https://www.stackshare.io"
echo "   Action: Create account → Submit tool → Add link"
echo ""

# Developer
echo "=== Developer Platforms ==="
echo "11. Dev.to"
echo "   URL: https://dev.to"
echo "   Action: Create account → Write article → Add link"
echo ""
echo "12. Hashnode.dev"
echo "   URL: https://hashnode.dev"
echo "   Action: Create account → Write article → Add link"
echo ""
echo "13. Medium.com"
echo "   URL: https://medium.com"
echo "   Action: Create account → Write article → Add link"
echo ""
echo "14. LinkedIn Articles"
echo "   URL: https://www.linkedin.com"
echo "   Action: Create account → Write article → Add link"
echo ""

# Code Platforms
echo "=== Code Platforms ==="
echo "15. CodePen.io"
echo "   URL: https://codepen.io"
echo "   Action: Create account → Create pen → Add link"
echo ""
echo "16. CodeSandbox.io"
echo "   URL: https://codesandbox.io"
echo "   Action: Create account → Create sandbox → Add link"
echo ""
echo "17. StackBlitz.com"
echo "   URL: https://stackblitz.com"
echo "   Action: Create account → Create project → Add link"
echo ""
echo "18. JSFiddle.net"
echo "   URL: https://jsfiddle.net"
echo "   Action: Create account → Create fiddle → Add link"
echo ""

# General
echo "=== General Directories ==="
echo "19. SourceForge.net"
echo "   URL: https://sourceforge.net"
echo "   Action: Create account → Submit project → Add link"
echo ""
echo "20. ProductHunt.com"
echo "   URL: https://www.producthunt.com"
echo "   Action: Already listed above (#8)"
echo ""

echo "================================================"
echo "  Submission Checklist"
echo "================================================"
echo ""
echo "For each directory:"
echo "  [ ] Create account"
echo "  [ ] Verify email"
echo "  [ ] Submit project"
echo "  [ ] Add description"
echo "  [ ] Add link to wikipept.com"
echo "  [ ] Screenshot/logo if available"
echo ""
echo "After submission:"
echo "  [ ] Track all links in a spreadsheet"
echo "  [ ] Update README.md with directory links"
echo "  [ ] Monitor for approval"
echo ""
echo "Project Links:"
echo "  Website: https://wikipept.com"
echo "  GitHub: https://github.com/pepwiki"
echo "  Gists:"
echo "    - https://gist.github.com/pepwiki/33052f4717b2d00826c5822303f7d72c"
echo "    - https://gist.github.com/pepwiki/9938ca78b2aa82b840756528b4f7747b"
echo "    - https://gist.github.com/pepwiki/b4c022a1a965adabec22698b11541c72"
echo "    - https://gist.github.com/pepwiki/c1b84bede0179f244bbaa5bc3d2f226d"
echo "    - https://gist.github.com/pepwiki/4522d2c91f8be31c914f7f0ef1d2b305"
echo "    - https://gist.github.com/pepwiki/b572bb64d2484bcb4d1afccde126b411"
echo "    - https://gist.github.com/pepwiki/aeeb1c7523dd54b69345e6bdb62d5149"
echo "    - https://gist.github.com/pepwiki/3f337ae51a0492425ebe196aa0cec465"
echo ""
echo "Done! Good luck with submissions."
